name: 'Npm pre-release detection'
description: 'This action detects pre-release Npm packages for a given package file.'
inputs:
  package-file-full-path:
    description: 'The name of the package file'
    required: true
outputs:
  found-pre-release:
    description: 'Boolean indicator used to tell that a pre-release packages was found.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: "package"
  color: "green"
