name: Pull CI

on:
  pull_request:
    branches: '*'
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Print Node Version
      run: node --version
    - name: Install Dependencies
      run: npm ci
    - run: npm run build --if-present
    - run: npm install -g eslint
    - name: Run ESLint
      run: eslint .
    - run: npm test
    - run: npm i -g @vercel/ncc
    - name: Run ncc build root
      run: npm run-script buildnccroot
    - name: Action end-to-end test
      uses: ./
      id: npmprerelease
      with:
        package-file-full-path: ./package.json
    - run: echo "result ${{ steps.npmprerelease.outputs.found-pre-release }}"
